In [0]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle (1).json


{'kaggle.json': b'{"username":"piyushbhojwani","key":"4d88de0c15dcb19a7e7463e02deb7116"}'}

In [0]:
!pip install -q kaggle

In [0]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [0]:
!chmod 600 ~/.kaggle/kaggle.json

In [0]:
!kaggle datasets download -d prasunroy/natural-images

natural-images.zip: Skipping, found more recently modified local copy (use --force to force download)


In [0]:
from zipfile import ZipFile

In [0]:
#z=ZipFile('/content/natural-images.zip')
import os
import zipfile

local_zip = '/content/natural-images.zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
zip_ref.extractall('/content/natural-images')

In [0]:
#z.infolist()
zip_ref.infolist()

[<ZipInfo filename='natural_images/' filemode='?-----x---' external_attr=0x10>,
 <ZipInfo filename='natural_images/airplane/' filemode='?-----x---' external_attr=0x10>,
 <ZipInfo filename='natural_images/airplane/airplane_0000.jpg' compress_type=deflate external_attr=0x20 file_size=14425 compress_size=14265>,
 <ZipInfo filename='natural_images/airplane/airplane_0001.jpg' compress_type=deflate external_attr=0x20 file_size=13631 compress_size=13464>,
 <ZipInfo filename='natural_images/airplane/airplane_0002.jpg' compress_type=deflate external_attr=0x20 file_size=16170 compress_size=16011>,
 <ZipInfo filename='natural_images/airplane/airplane_0003.jpg' compress_type=deflate external_attr=0x20 file_size=14762 compress_size=14530>,
 <ZipInfo filename='natural_images/airplane/airplane_0004.jpg' compress_type=deflate external_attr=0x20 file_size=14517 compress_size=14350>,
 <ZipInfo filename='natural_images/airplane/airplane_0005.jpg' compress_type=deflate external_attr=0x20 file_size=14815 c

In [0]:
train_airplane_dir = os.path.join('/content/natural-images/natural_images/airplane')
train_car_dir = os.path.join('/content/natural-images/natural_images/car')
train_cat_dir = os.path.join('/content/natural-images/natural_images/cat')
train_dog_dir = os.path.join('/content/natural-images/natural_images/dog')
train_flower_dir = os.path.join('/content/natural-images/natural_images/flower')
train_fruit_dir = os.path.join('/content/natural-images/natural_images/fruit')
train_motorbike_dir = os.path.join('/content/natural-images/natural_images/motorbike')
train_person_dir = os.path.join('/content/natural-images/natural_images/person')

In [0]:
train_airplane_names = os.listdir(train_airplane_dir)
train_car_names = os.listdir(train_car_dir)
train_cat_names = os.listdir(train_cat_dir)
train_dog_names = os.listdir(train_dog_dir)
train_flower_names = os.listdir(train_flower_dir)
train_fruit_names = os.listdir(train_fruit_dir)
train_motorbike_names = os.listdir(train_motorbike_dir)
train_person_names = os.listdir(train_person_dir)

In [0]:
print(train_airplane_names[:20])

['airplane_0663.jpg', 'airplane_0075.jpg', 'airplane_0410.jpg', 'airplane_0152.jpg', 'airplane_0306.jpg', 'airplane_0615.jpg', 'airplane_0542.jpg', 'airplane_0572.jpg', 'airplane_0377.jpg', 'airplane_0636.jpg', 'airplane_0688.jpg', 'airplane_0050.jpg', 'airplane_0136.jpg', 'airplane_0298.jpg', 'airplane_0036.jpg', 'airplane_0473.jpg', 'airplane_0617.jpg', 'airplane_0231.jpg', 'airplane_0562.jpg', 'airplane_0286.jpg']


In [0]:
print('total training airplane images:', len(os.listdir(train_airplane_dir)))
print('total training car images:', len(os.listdir(train_car_dir)))
print('total training cat images:', len(os.listdir(train_cat_dir)))
print('total training dog images:', len(os.listdir(train_dog_dir)))
print('total training flower images:', len(os.listdir(train_flower_dir)))
print('total training fruit images:', len(os.listdir(train_fruit_dir)))
print('total training motorbike images:', len(os.listdir(train_motorbike_dir)))
print('total training person images:', len(os.listdir(train_person_dir)))

total training airplane images: 727
total training car images: 968
total training cat images: 885
total training dog images: 702
total training flower images: 843
total training fruit images: 1000
total training motorbike images: 788
total training person images: 986


In [0]:
%matplotlib inline

import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Parameters for our graph; we'll output images in a 4x4 configuration
nrows = 4
ncols = 4

# Index for iterating over images
pic_index = 0

In [0]:
import tensorflow as tf

In [0]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# All images will be rescaled by 1./255
datagen = ImageDataGenerator(validation_split=0.2,rescale=1/255)
#validation_datagen = ImageDataGenerator(rescale=1/255)

# Flow training images in batches of 128 using train_datagen generator
train_generator = datagen.flow_from_directory(
        '/content/natural-images/natural_images',  # This is the source directory for training images
        target_size=(300, 300),  # All images will be resized to 150x150
        batch_size=128,
        subset='training',
        # Since we use binary_crossentropy loss, we need binary labels
        class_mode='binary')

# Flow training images in batches of 128 using train_datagen generator
validation_generator = datagen.flow_from_directory(
        '/content/natural-images/natural_images',  # This is the source directory for training images
        target_size=(300, 300),  # All images will be resized to 150x150
        batch_size=32,
        subset='validation',
        #Since we use binary_crossentropy loss, we need binary labels
        class_mode='binary')

Found 5522 images belonging to 8 classes.
Found 1377 images belonging to 8 classes.


In [0]:
for image_batch,label_batch in train_generator:
  print("Image batch shape: ", image_batch.shape)
  print("Labe batch shape: ", label_batch.shape)
  break

Image batch shape:  (128, 300, 300, 3)
Labe batch shape:  (128,)


In [0]:
for image_batch1,label_batch1 in validation_generator:
  print("Image batch shape: ", image_batch1.shape)
  print("Labe batch shape: ", label_batch1.shape)
  break

Image batch shape:  (32, 300, 300, 3)
Labe batch shape:  (32,)


In [0]:
from keras.preprocessing import image
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
import numpy as np

model = VGG16(weights='imagenet', include_top=False)
model.summary()
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, None, None, 3)     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, None, None, 128)   0         
__________

ValueError: ignored

In [0]:
img_path = '/content/natural-images/natural_images/car/car_0004.jpg'
img = image.load_img(img_path, target_size=(224, 224)) # default img_path
img_data = image.img_to_array(img)
img_data = np.expand_dims(img_data, axis=0)
img_data = preprocess_input(img_data)

vgg16_feature = model.predict(img_data)

print(vgg16_feature.shape)
print(vgg16_feature)

(1, 7, 7, 512)
[[[[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   ...
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]]

  [[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]
   ...
   [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
    0.0000000e+00 0.0000000e+00]

In [0]:
from keras.applications.vgg16 import preprocess_input
vgg16_feature_list = []

for idx, dirname in enumerate('/content/natural-images/natural_images/car'):
    # get the directory names, i.e., 'dogs' or 'cats'
    # ...
    
    for i, fname in enumerate('car'):
        # process the files under the directory 'dogs' or 'cats'
        # ...
        
        img = image.load_img(img_path, target_size=(224, 224))
        img_data = image.img_to_array(img)
        img_data = np.expand_dims(img_data, axis=0)
        img_data = preprocess_input(img_data)

        vgg16_feature = model.predict(img_data)
        vgg16_feature_np = np.array(vgg16_feature)
        vgg16_feature_list.append(vgg16_feature_np.flatten())
        
vgg16_feature_list_np = np.array(vgg16_feature_list)
#kmeans = KMeans(n_clusters=2, random_state=0).fit(vgg16_feature_list_np)
print(vgg16_feature_list_np)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# Query Image

In [0]:
img_path = '/content/natural-images/natural_images/car/car_0004.jpg'
img = image.load_img(img_path, target_size=(224, 224)) 
img_data = image.img_to_array(img)
img_data = np.expand_dims(img_data, axis=0)
img_data = preprocess_input(img_data)

vgg16_feature = model.predict(img_data)

print(vgg16_feature.shape)
print(vgg16_feature)

# KD Tree

In [0]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=10, algorithm='kd_tree').fit(vgg16_feature_list_np)
distances, indices = nbrs.kneighbors(vgg16_feature_list_np)
indices


array([[  1,   7,   3, ...,  61, 125,   5],
       [  1,   7,   3, ...,  61, 125,   5],
       [  1,   7,   3, ...,  61, 125,   5],
       ...,
       [  1,   7,   3, ...,  61, 125,   5],
       [  1,   7,   3, ...,  61, 125,   5],
       [  1,   7,   3, ...,  61, 125,   5]])